default_config:

#### python scripts extension. Python scripts goes on folder /python_scripts
python_script:

recorder:
  purge_keep_days: 7
  db_url: sqlite:////config/home-assistant_v2.db

### HA FRONTENDS
frontend:
  themes: !include_dir_merge_named hakairos-configuration/frontend/community/themes/

lovelace:
  mode: yaml
  resources:
    - url: /local/button-card/button-card.js
      type: module
    - url: /local/clockwork-card/clockwork-card.js
      type: module
    - url: /local/kiosk-mode/kiosk-mode.js
      type: module
    - url: /local/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/themes/kairoshub.css
      type: css
    - url: /local/time-picker-card/time-picker-card.js
      type: module
    - url: /local/weather-card/weather-card.js
      type: module
    - url: /local/kt-light-entity-card/light-entity-card.js
      type: module

  dashboards:
    lovelace-kairoshub:
      mode: yaml
      title: Home
      icon: mdi:help
      show_in_sidebar: true
      filename: lovelace-kairoshome.yaml

#### HA Custom Events extension
ha-custom-events: !include_dir_merge_named hakairos-configuration/hacustomevents/

#### HA Kafka extension
hakafka: !include_dir_merge_named hakairos-configuration/hakafka/

#### input text
input_text: !include hakairos-configuration/hassio-config/input_text.yaml

#### input select
input_select: !include hakairos-configuration/hassio-config/input_select.yaml

##### input number
input_number: !include hakairos-configuration/hassio-config/input_number.yaml

##### datetime
input_datetime: !include hakairos-configuration/hassio-config/input_datetime.yaml

##### input boolean
input_boolean: !include hakairos-configuration/hassio-config/input_boolean.yaml

#thermostat
# climate: !include hakairos-configuration/hassio-config/climate.yaml

#switch thermostat
switch: !include hakairos-configuration/hassio-config/switch.yaml

# SENSOR
sensor: !include_dir_merge_list hakairos-configuration/hassio-config/sensor

# binary_sensor
binary_sensor: !include hakairos-configuration/hassio-config/binary_sensor.yaml

#contabilizzatori
utility_meter: !include hakairos-configuration/hassio-config/utility_meter.yaml

# covers
cover: !include_dir_merge_list hakairos-configuration/hassio-config/cover

#### hassio groups
group: !include_dir_merge_named hakairos-configuration/hassio-config/group

#### automations
automation: !include_dir_merge_list hakairos-configuration/hassio-config/automation

light: !include_dir_merge_list hakairos-configuration/hassio-config/light


#### logger configuration
logger:
  default: info
  logs:
    homeassistant.components.cloud: info
    custom_components.hakafka: info
    custom_components.ha-custom-events: info
